
# Database Resource names and suffixes
STRUCTURAL_PREPROC_RESOURCE_NAME="Structural_preproc"
FUNCTIONAL_PREPROC_RESOURCE_SUFFIX="_preproc"
FIX_PROC_RESOURCE_SUFFIX="_FIX"
POSTFIX_PROC_RESOURCE_SUFFIX="_PostFix"
RESTING_STATE_STATS_PROC_RESOURCE_SUFFIX="_RSS"
MSM_ALL_REGISTRATION_RESOURCE_NAME="MSMAllReg"

