#!/bin/bash

if [ -z "${XNAT_PBS_JOBS}" ]; then
	echo "$(basename ${0}): ABORTING: XNAT_PBS_JOBS environment variable must be set"
	exit 1
fi

version_file="${XNAT_PBS_JOBS}/version.txt"
deployment_file="${XNAT_PBS_JOBS}/deployment.txt"

cat ${version_file}
if [ -e "${deployment_file}" ] ; then
	cat ${deployment_file}
fi
