#!/bin/bash

source ${1}/xnat_pbs_setup ${2}
export PATH=/act/Anaconda3-2.3.0/bin:${PATH}
export CLUSTER="2.0"

if [ -z "${XNAT_PBS_JOBS}" ]; then
	script_name=$(basename "${0}")
	echo "${script_name}: ABORTING: XNAT_PBS_JOBS environment variable must be set"
	exit 1
fi

source ${XNAT_PBS_JOBS}/shlib/utils.shlib
set_g_python_environment
source activate ${g_python_environment} 2>/dev/null
${XNAT_PBS_JOBS}/lib/ccf/structural_preprocessing/one_subject_job_submitter.py ${@:3}
source deactivate 2>/dev/null
